export const SET_USER = "SET_USER";
export const GET_USER = "GET_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const REGISTER_REQUEST = "USERS_REGISTER_REQUEST";
export const REGISTER_SUCCESS = "USERS_REGISTER_SUCCESS";
export const REGISTER_FAILURE = "USERS_REGISTER_FAILURE";

export const LOGIN_REQUEST = "USERS_LOGIN_REQUEST";
export const LOGIN_SUCCESS = "USERS_LOGIN_SUCCESS";
export const LOGIN_FAILURE = "USERS_LOGIN_FAILURE";

export const LOGOUT = "USERS_LOGOUT";

export const GETALL_REQUEST = "USERS_GETALL_REQUEST";
export const GETALL_SUCCESS = "USERS_GETALL_SUCCESS";
export const GETALL_FAILURE = "USERS_GETALL_FAILURE";

export const DELETE_REQUEST = "USERS_DELETE_REQUEST";
export const DELETE_SUCCESS = "USERS_DELETE_SUCCESS";
export const DELETE_FAILURE = "USERS_DELETE_FAILUR";

export const SUCCESS = "ALERT_SUCCESS";
export const ERROR = "ALERT_ERROR";
export const CLEAR = "ALERT_CLEAR";

export const ADD_PATIENT_REQUEST = "ADD_PATIENT_REQUEST"
export const ADD_PATIENT_SUCCESS = "ADD_PATIENT_SUCCESS"
export const ADD_PATIENT_FAILURE = "ADD_PATIENT_FAILURE"

export const DELETE_PATIENT_REQUEST = "DELETE_PATIENT_REQUEST";
export const DELETE_PATIENT_SUCCESS = "DELETE_PATIENT_SUCCESS";
export const DELETE_PATIENT_FAILURE = "DELETE_PATIENT_FAILURE";

export const GETALL_PATIENT_REQUEST = "GETALL_PATIENT_REQUEST"
export const GETALL_PATIENT_SUCCESS = "GETALL_PATIENT_SUCCESS"
export const GETALL_PATIENT_FAILURE = "GETALL_PATIENT_FAILURE"

export const GET_PATIENTS_BYID_REQUEST = "GET_PATIENTS_BYID_REQUEST"
export const GET_PATIENTS_BYID_SUCCESS = "GET_PATIENTS_BYID_SUCCESS"
export const GET_PATIENTS_BYID_FAILURE = "GET_PATIENTS_BYID_FAILURE"

export const GET_PATIENTS_PRINT_REQUEST = "GET_PATIENTS_PRINT_REQUEST"
export const GET_PATIENTS_PRINT_SUCCESS = "GET_PATIENTS_PRINT_SUCCESS"
export const GET_PATIENTS_PRINT_FAILURE = "GET_PATIENTS_PRINT_FAILURE"

